Ars Technica:
  include:
  - ^https://arstechnica.com/(\w+)/(\d+)/(\d+)/
  title: Ars Technica
  url: https://arstechnica.com/ai/
Bloomberg:
  include:
  - ^https://www.bloomberg.com/news/
  title: Bloomberg
  url: https://www.bloomberg.com/ai
Business Insider:
  exclude:
  - ^https://www.insider.com
  - ^https://www.passionfroot.me
  title: Business Insider
  url: https://www.businessinsider.com/tech
FT:
  include:
  - https://www.ft.com/content/
  title: FT
  url: https://www.ft.com/technology
Feedly AI:
  exclude:
  - ^https://feedly.com
  - ^https://s1.feedly.com
  - ^https://blog.feedly.com
  scroll: 5
  initial_sleep: 30
  title: Feedly AI
  url: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMiLCJzYWxpZW5jZSI6ImFib3V0In1dLCJidW5kbGVzIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC9jYXRlZ29yeS9HYWRnZXRzIn1dfQ
# Google News:  # started blocking more effectively
# should try to search news for 'artificial intelligence' with the google API https://proxiesapi.com/articles/fetching-news-articles-with-the-google-news-api-and-python
# Google News AI:
#   click: //*[@aria-label="Artificial intelligence"]
#   include:
#   - ^https://news.google.com/read/
#   scroll: 1
#   title: Google News - Technology - Artificial intelligence
#   url: https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen
Hacker News 1:
  exclude:
  - https://news.ycombinator.com/
  - https://www.ycombinator.com/
  title: Hacker News 1
  url: https://news.ycombinator.com/
  minlength: 5
Hacker News 2:
  exclude:
  - https://news.ycombinator.com
  - https://www.ycombinator.com
  title: Hacker News 2
  url: https://news.ycombinator.com/?p=2
HackerNoon:
  exclude:
  - ^https://hackernoon.com/$
  - ^https://hackernoon.com/c$
  - ^https://hackernoon.com/coins$
  - ^https://hackernoon.com/companies$
  - ^https://hackernoon.com/gallery$
  - ^https://hackernoon.com/how-to-gain-followers-and-newsletter-subs-directly-on-hackernoon$
  - ^https://hackernoon.com/login$
  - ^https://hackernoon.com/reader-boot$
  - ^https://hackernoon.com/sitemap.xml$
  - ^https://hackernoon.com/startups$
  - ^https://hackernoon.com/techbeat$
  - ^https://hackernoon.com/why-i-write-on-hacker-noon-nl28335q$
  - ^https://hackernoon.com/writer-signup$
  title: HackerNoon
  url: https://hackernoon.com/
New York Times:
  include:
  - ^https://www.nytimes.com/(\d+)/(\d+)/(\d+)/
  title: New York Times
  url: https://www.nytimes.com/section/technology
Reddit:
  exclude:
  - ^https://chat.reddit.com/
  - ^https://i.redd.it/
  - ^https://redditblog.com/
  - ^https://www.redditinc.com/
  - ^https://www.reddithelp.com/
  - ^https://itunes.apple.com/
  - ^https://play.google.com/
  scroll: 2
  minlength: 8
  title: Reddit
  url: https://www.reddit.com/r/AI_Agents+AIethics+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+ControlProblem+Futurology+MachineLearning+OpenAI+ProgrammerHumor+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
  # url: https://www.reddit.com/r/ChatGPT
Techmeme:
  exclude:
  - ^https://www.techmeme.com
  - ^https://twitter.com/
  - ^https://www.threads.net
  - ^https://www.linkedin.com
  - ^https://mastodon.social
  - ^https://bsky.app
  title: Techmeme
  url: https://www.techmeme.com/river
The Register:
  include:
  - ^https://www.theregister.com/(\d+)/(\d+)/(\d+)/
  title: The Register
  url: https://www.theregister.com/software/ai_ml/
The Verge:
  include:
  - ^https://www.theverge.com/news
  title: The Verge
  url: https://www.theverge.com/ai-artificial-intelligence
VentureBeat:
  title: VentureBeat
  url: https://venturebeat.com/category/ai/
WSJ:
  title: WSJ
  url: https://www.wsj.com/tech/ai
Washington Post:
  include:
  - https://www.washingtonpost.com/(\w+)/(\d+)/(\d+)/(\d+)/
  title: Washington Post
  url: https://www.washingtonpost.com/technology/innovations/
