Ars Technica:
  type: html
  url: https://arstechnica.com/ai/
  rss: https://arstechnica.com/ai/feed/
  include:
  - ^https://arstechnica.com/(\w+)/(\d+)/(\d+)/
  title: Ars_Technica

Bloomberg:
  type: html
  include:
  - ^https://www.bloomberg.com/news/
  title: Bloomberg
  url: https://www.bloomberg.com/ai
  rss: https://feeds.bloomberg.com/technology/news.rss

Business Insider:
  type: html
  exclude:
  - ^https://www.insider.com
  - ^https://www.passionfroot.me
  title: Business_Insider
  url: https://www.businessinsider.com/tech

FT:
  type: html
  include:
  - https://www.ft.com/content/
  title: FT
  url: https://www.ft.com/artificial-intelligence
  rss: https://www.ft.com/artificial-intelligence?format=rss

Feedly AI:
  type: html
  exclude:
  - ^https://feedly.com
  - ^https://s1.feedly.com
  - ^https://blog.feedly.com
  scroll: 3   # page down times for infinite scroll
  initial_sleep: 20
  title: Feedly_AI
  url: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMiLCJzYWxpZW5jZSI6ImFib3V0In1dLCJidW5kbGVzIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC9jYXRlZ29yeS9HYWRnZXRzIn1dfQ

# Google News:  # started blocking more effectively
# # could try to search news for 'artificial intelligence' with the google API https://proxiesapi.com/articles/fetching-news-articles-with-the-google-news-api-and-python
# # added google news rss feed to feedly
#   type: html
#   click: //*[@aria-label="Artificial intelligence"]
#   include:
#   - ^https://news.google.com/read/
#   scroll: 1
#   title: Google_News
#   url: https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen
#   rss: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en

Hacker News 1:
  type: html
  exclude:
  - https://news.ycombinator.com/
  - https://www.ycombinator.com/
  title: Hacker_News_1
  url: https://news.ycombinator.com/
  rss: https://news.ycombinator.com/rss
  minlength: 5

Hacker News 2:
  type: html
  exclude:
  - https://news.ycombinator.com
  - https://www.ycombinator.com
  title: Hacker_News_2
  url: https://news.ycombinator.com/?p=2

HackerNoon:
  type: html
  exclude:
  - ^https://hackernoon.com/$
  - ^https://hackernoon.com/c$
  - ^https://hackernoon.com/coins$
  - ^https://hackernoon.com/companies$
  - ^https://hackernoon.com/gallery$
  - ^https://hackernoon.com/how-to-gain-followers-and-newsletter-subs-directly-on-hackernoon$
  - ^https://hackernoon.com/login$
  - ^https://hackernoon.com/reader-boot$
  - ^https://hackernoon.com/sitemap.xml$
  - ^https://hackernoon.com/startups$
  - ^https://hackernoon.com/techbeat$
  - ^https://hackernoon.com/why-i-write-on-hacker-noon-nl28335q$
  - ^https://hackernoon.com/writer-signup$
  title: HackerNoon
  url: https://hackernoon.com/tagged/ai
  rss: https://hackernoon.com/tagged/ai/feed
  
New York Times:
  type: html
  include:
  - ^https://www.nytimes.com/(\d+)/(\d+)/(\d+)/
  title: New_York_Times
  url: https://www.nytimes.com/section/technology
  rss: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml  
  initial_sleep: 20

Reddit:
  type: html
  exclude:
  - ^https://www.reddit.com/user/
  - ^https://www.reddit.com/domain/
  - ^https://chat.reddit.com/
  - ^https://i.redd.it/
  - ^https://redditblog.com/
  - ^https://www.redditinc.com/
  - ^https://www.reddithelp.com/
  - ^https://itunes.apple.com/
  - ^https://play.google.com/
  - ^https?://(?:www\.)?reddit\.com/r/([^/]+)/?$
  - ^https://www.reddit.com/help/
  - ^https://www.reddit.com/contact/
  - ^https://www.reddit.com/rules/
  scroll: 5
  minlength: 8
  title: Reddit
  url: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
  rss: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/.rss?sort=top&t=day

Techmeme:
  type: html
  exclude:
  - ^https://www.techmeme.com
  - ^https://twitter.com/
  - ^https://www.threads.net
  - ^https://www.linkedin.com
  - ^https://mastodon.social
  - ^https://bsky.app
  title: Techmeme
  url: https://www.techmeme.com/river
  rss: https://www.techmeme.com/feed.xml

The Register:
  type: html
  include:
  - ^https://www.theregister.com/(\d+)/(\d+)/(\d+)/
  title: The_Register
  url: https://www.theregister.com/software/ai_ml/
  rss: https://www.theregister.com/software/ai_ml/headlines.atom

The Verge:
  type: html
  include:
  - ^https://www.theverge.com/news
  title: The_Verge
  url: https://www.theverge.com/ai-artificial-intelligence
  rss: https://www.theverge.com/rss/ai-artificial-intelligence/index.xml

VentureBeat:
  type: html
  title: VentureBeat
  url: https://venturebeat.com/category/ai/
  rss: https://venturebeat.com/category/ai/feed/

WSJ:
  type: html
  title: WSJ
  url: https://www.wsj.com/tech/ai
  rss: https://feeds.a.dj.com/rss/RSSWSJD.xml
  
Washington Post:
  type: html
  include:
  - https://www.washingtonpost.com/(\w+)/(\d+)/(\d+)/(\d+)/
  title: Washington_Post
  url: https://www.washingtonpost.com/technology/innovations/
  rss: https://feeds.washingtonpost.com/rss/business/technology

The Guardian:
  type: html
  include:
  - https://www.theguardian.com/
  title: The_Guardian
  url: https://www.theguardian.com/uk/technology
  rss: https://www.theguardian.com/uk/technology/rss

NewsAPI:
  type: rest
  url: https://newsapi.org/v2/everything
  title: NewsAPI
  function_name: fn_extract_newsapi

# to possibly add:
# papers with code trending
# to scale it, would probably pay for newsapi, newscatcher, gnews.io
