"""Description: Constants, including configs and prompts for AInewsbot project"""
import os
import dotenv
dotenv.load_dotenv()

REQUEST_TIMEOUT = 120

DOWNLOAD_DIR = "htmldata"
PAGES_DIR = 'htmlpages'
SCREENSHOT_DIR = 'screenshots'

if not os.path.exists(DOWNLOAD_DIR):
    os.makedirs(DOWNLOAD_DIR)
if not os.path.exists(PAGES_DIR):
    os.makedirs(PAGES_DIR)
if not os.path.exists(SCREENSHOT_DIR):
    os.makedirs(SCREENSHOT_DIR)

# Path to browser app
# FIREFOX_APP_PATH = '/Applications/Firefox.app'
# Path to profile
# FIREFOX_PROFILE_PATH = '/Users/drucev/Library/Application Support/Firefox/Profiles/k8k0lcjj.default-release'
FIREFOX_PROFILE_PATH = '/Users/drucev/Library/Application Support/Firefox/Profiles/j6cl7lzz.playwright'
# CHROME_PROFILE_PATH = '/Users/drucev/Library/Application Support/Google/Chrome'
# CHROME_PROFILE = 'Profile 7'
# CHROME_DRIVER_PATH = '/Users/drucev/Library/Application Support/undetected_chromedriver/undetected_chromedriver'
SLEEP_TIME = 10
# NUM_BROWSERS = 4
# BROWSERS = []

SQLITE_DB = 'articles.db'

# note that token count may not be accurate for eg google, anthropic

MAX_INPUT_TOKENS = 8192     # includes text of all headlines
# MAX_OUTPUT_TOKENS = 4096    # max in current model
TENACITY_RETRY = 5  # Maximum 5 attempts

# TEMPERATURE = 0

SOURCECONFIG = "sources.yaml"
SOURCES_EXPECTED = 16
MIN_TITLE_LEN = 28
MINIMUM_STORY_RATING = 2
# MAXPAGELEN = 50

HOSTNAME_SKIPLIST = ['finbold.com']
SITE_NAME_SKIPLIST = ['finbold']

MODEL_FAMILY = {'gpt-4o-2024-11-20': 'openai',
                'gpt-4o-mini': 'openai',
                'o4-mini': 'openai',
                'o3-mini': 'openai',
                'gpt-4.5-preview': 'openai',
                'gpt-4.1': 'openai',
                'gpt-4.1-mini': 'openai',
                'models/gemini-2.0-flash-thinking-exp': 'google',
                'models/gemini-2.0-pro-exp': 'google',
                'models/gemini-2.0-flash': 'google',
                'models/gemini-1.5-pro-latest': 'google',
                'models/gemini-1.5-pro': 'google',
                }

CANONICAL_TOPICS = [
    "Policy and regulation",
    "Economics",
    "Governance",
    "Safety and Alignment",
    "Bias and Fairness",
    "Privacy & Surveillance",
    "Inequality",
    "Job Automation",
    'Disinformation',
    'Deepfakes',
    'Sustainability',

    "Virtual Assistants",
    "Chatbots",
    "Robots",
    "Autonomous vehicles",
    "Drones",
    'Virtual & Augmented Reality',

    # 'Machine learning',
    # 'Deep Learning',
    # "Neural Networks",
    # "Generative Adversarial Networks",

    'Reinforcement Learning',
    'Language Models',
    'Transformers',
    'Gen AI',
    'Retrieval Augmented Generation',
    "Computer Vision",
    'Facial Recognition',
    'Speech Recognition & Synthesis',

    'Open Source',

    'Internet of Things',
    'Quantum Computing',
    'Brain-Computer Interfaces',

    "Hardware",
    "Infrastructure",
    'Semiconductor Chips',
    'Neuromorphic Computing',

    "Healthcare",
    "Fintech",
    "Education",
    "Entertainment",
    "Funding",
    "Venture Capital",
    "Mergers and acquisitions",
    "Deals",
    "IPOs",
    "Ethics",
    "Legal issues",
    "Cybersecurity",
    "AI doom",
    'Stocks',
    'Bubble',
    'Cryptocurrency',
    'Climate',
    'Energy',
    'Nuclear',
    'Scams',
    'Privacy',
    'Intellectual Property',
    'Code assistants',
    'Customer service',
    'Military',
    'Agriculture',
    'Testing',
    'Authors & Writing',
    'Books & Publishing',
    'TV & Film & Movies',
    'Streaming',
    'Hollywood',
    'Music',
    'Art & Design',
    'Fashion',
    'Food & Drink',
    'Travel',
    'Health & Fitness',
    'Sports',
    'Gaming',
    # 'Science',
    'Politics',
    'Finance',
    'History',
    'Society & Culture',
    'Lifestyle & Travel',
    'Jobs & Careers',
    'Labor Market',
    'Products',
    'Opinion',
    'Review',
    'Cognitive Science',
    'Consciousness',
    'Artificial General Intelligence',
    'Singularity',
    'Manufacturing',
    'Supply chain optimization',
    'Transportation',
    'Smart grid',
    'Recommendation systems',

    # 'Nvidia',
    # 'Google',
    # 'OpenAI',
    # 'Meta',
    # 'Apple',
    # 'Microsoft',
    # 'Perplexity',
    # 'Salesforce',
    # 'Uber',
    # 'AMD',
    # 'Netflix',
    # 'Disney',
    # 'Amazon',
    # 'Cloudflare',
    # 'Anthropic',
    # 'Cohere',
    # 'Baidu',
    # 'Big Tech',
    # 'Samsung',
    # 'Tesla',
    # 'Reddit',
    # "DeepMind",
    # "Intel",
    # "Qualcomm",
    # "Oracle",
    # "SAP",
    # "Alibaba",
    # "Tencent",
    # "Hugging Face",
    # "Stability AI",
    # "Midjourney",
    # 'WhatsApp',

    # 'ChatGPT',
    # 'Gemini',
    # 'Claude',
    # 'Copilot',

    # 'Elon Musk',
    # 'Bill Gates',
    # 'Sam Altman',
    # 'Mustafa Suleyman',
    # 'Sundar Pichai',
    # 'Yann LeCun',
    # 'Geoffrey Hinton',
    # 'Mark Zuckerberg',
    # "Demis Hassabis",
    # "Andrew Ng",
    # "Yoshua Bengio",
    # "Ilya Sutskever",
    # "Dario Amodei",
    # "Richard Socher",
    # "Sergey Brin",
    # "Larry Page",
    # "Satya Nadella",
    # "Jensen Huang",

    'China',
    'European Union',
    'UK',
    'Russia',
    'Japan',
    'India',
    'Korea',
    'Taiwan',
]

######################################################################
# arbitrary, could start with e.g. Alexa rank, Google PageRank, Cloudflare Radar rank, SimilarWeb traffic, SEMrush, Ahrefs, Moz, Majestic, etc.
# don't really need 0s, can just .get() and default to 0
SOURCE_REPUTATION = {
    'Reddit': 0,
    'aitoolsclub.com': 0,
    'analyticsindiamag.com': 0,
    'aws.amazon.com': 0,
    'biztoc.com': 0,
    'blog.google': 0,
    'economictimes.indiatimes.com': 0,
    'finbold.com': 0,
    'flip.it': 0,
    'flipboard.com': 0,
    'github.com': 0,
    'greekreporter.com': 0,
    'medium.com': 0,
    'neurosciencenews.com': 0,
    'restofworld.org': 0,
    'sea.mashable.com': 0,
    'slashdot.org': 0,
    't.co': 0,
    'tech.co': 0,
    'tech.slashdot.org': 0,
    'telecomtalk.info': 0,
    'uxdesign.cc': 0,
    'v.redd.it': 0,
    'www.androidauthority.com': 0,
    'www.androidcentral.com': 0,
    'www.androidheadlines.com': 0,
    'www.androidpolice.com': 0,
    'www.benzinga.com': 0,
    'www.channelnewsasia.com': 0,
    'www.christopherspenn.com': 0,
    'www.ciodive.com': 0,
    'www.computerweekly.com': 0,
    'www.creativebloq.com': 0,
    'www.digitalcameraworld.com': 0,
    'www.digitaljournal.com': 0,
    'www.digitaltrends.com': 0,
    'www.entrepreneur.com': 0,
    'www.etfdailynews.com': 0,
    'www.euronews.com': 0,
    'www.finextra.com': 0,
    'www.fool.com': 0,
    'www.foxnews.com': 0,
    'www.globenewswire.com': 0,
    'www.investing.com': 0,
    'www.itpro.com': 0,
    'www.jpost.com': 0,
    'www.laptopmag.com': 0,
    'www.livemint.com': 0,
    'www.livescience.com': 0,
    'www.miamiherald.com': 0,
    'www.mobileworldlive.com': 0,
    'www.msn.com': 0,
    'www.newsmax.com': 0,
    'www.reddit.com': 0,
    'www.sciencedaily.com': 0,
    'www.statnews.com': 0,
    'www.techdirt.com': 0,
    'www.techmonitor.ai': 0,
    'www.techtimes.com': 0,
    'www.the-sun.com': 0,
    'www.thebrighterside.news': 0,
    'www.thedrum.com': 0,
    'www.tipranks.com': 0,
    'www.trendhunter.com': 0,
    'www.uniladtech.com': 0,
    '247wallst.com': 1,
    '9to5google.com': 1,
    '9to5mac.com': 1,
    'VentureBeat': 1,
    'abcnews.go.com': 1,
    'apnews.com': 1,
    'appleinsider.com': 1,
    'arxiv.org': 1,
    'bgr.com': 1,
    'blogs.nvidia.com': 1,
    'decrypt.co': 1,
    'digiday.com': 1,
    'fortune.com': 1,
    'in.mashable.com': 1,
    'lifehacker.com': 1,
    'machinelearningmastery.com': 1,
    'mashable.com': 1,
    'me.mashable.com': 1,
    'newatlas.com': 1,
    'nypost.com': 1,
    'observer.com': 1,
    'petapixel.com': 1,
    'phys.org': 1,
    'qz.com': 1,
    'readwrite.com': 1,
    'spectrum.ieee.org': 1,
    'techxplore.com': 1,
    'theconversation.com': 1,
    'thehill.com': 1,
    'thenextweb.com': 1,
    'time.com': 1,
    'towardsdatascience.com': 1,
    'twitter.com': 1,
    'variety.com': 1,
    'venturebeat.com': 1,
    'www.404media.co': 1,
    'www.adweek.com': 1,
    'www.axios.com': 1,
    'www.barrons.com': 1,
    'www.bbc.com': 1,
    'www.cbsnews.com': 1,
    'www.cbssports.com': 1,
    'www.cnbc.com': 1,
    'www.cnn.com': 1,
    'www.extremetech.com': 1,
    'www.forbes.com': 1,
    'www.gadgets360.com': 1,
    'www.geekwire.com': 1,
    'www.geeky-gadgets.com': 1,
    'www.inc.com': 1,
    'www.macrumors.com': 1,
    'www.macworld.com': 1,
    'www.makeuseof.com': 1,
    'www.marktechpost.com': 1,
    'www.medianama.com': 1,
    'www.nbcnews.com': 1,
    'www.newsweek.com': 1,
    'www.nextbigfuture.com': 1,
    'www.npr.org': 1,
    'www.pcgamer.com': 1,
    'www.pcmag.com': 1,
    'www.pcworld.com': 1,
    'www.popsci.com': 1,
    'www.psychologytoday.com': 1,
    'www.pymnts.com': 1,
    'www.scmp.com': 1,
    'www.semafor.com': 1,
    'www.techinasia.com': 1,
    'www.techradar.com': 1,
    'www.techrepublic.com': 1,
    'www.techspot.com': 1,
    'www.theglobeandmail.com': 1,
    'www.theguardian.com': 1,
    'www.usatoday.com': 1,
    'www.windowscentral.com': 1,
    'Business Insider': 2,
    'HackerNoon': 2,
    'Techmeme': 2,
    'Techpresso': 2,
    'The Verge': 2,
    'WaPo Tech': 2,
    'arstechnica.com': 2,
    'ca.finance.yahoo.com': 2,
    'ca.news.yahoo.com': 2,
    'cacm.acm.org': 2,
    'consent.yahoo.com': 2,
    'finance.yahoo.com': 2,
    'financialpost.com': 2,
    'futurism.com': 2,
    'gizmodo.com': 2,
    'hackernoon.com': 2,
    'markets.businessinsider.com': 2,
    'news.yahoo.com': 2,
    'openai.com': 2,
    'siliconangle.com': 2,
    'simonwillison.net': 2,
    'techcrunch.com': 2,
    'uk.finance.yahoo.com': 2,
    'uk.news.yahoo.com': 2,
    'www.businessinsider.com': 2,
    'www.cnet.com': 2,
    'www.engadget.com': 2,
    'www.fastcompany.com': 2,
    'www.nature.com': 2,
    'www.newscientist.com': 2,
    'www.reuters.com': 2,
    'www.technologyreview.com': 2,
    'www.theatlantic.com': 2,
    'www.theinformation.com': 2,
    'www.tomsguide.com': 2,
    'www.tomshardware.com': 2,
    'www.washingtonpost.com': 2,
    'www.wired.com': 2,
    'www.yahoo.com': 2,
    'www.zdnet.com': 2,
    'www.theverge.com': 3,
    'www.theregister.com': 3,
    'The Register': 3,
    'go.theregister.com': 3,
    'Ars Technica': 3,
    'Bloomberg Tech': 4,
    'FT Tech': 4,
    'NYT Tech': 4,
    'WSJ Tech': 4,
    'news.bloomberglaw.com': 4,
    'www.bloomberg.com': 4,
    'www.ft.com': 4,
    'www.nytimes.com': 4,
    'www.wsj.com': 4,
}

######################################################################

# NEWSCATCHER_SOURCES = ['247wallst.com',
#                        '9to5mac.com',
#                        'androidauthority.com',
#                        'androidcentral.com',
#                        'androidheadlines.com',
#                        'appleinsider.com',
#                        'benzinga.com',
#                        'cnet.com',
#                        'cnn.com',
#                        'digitaltrends.com',
#                        'engadget.com',
#                        'fastcompany.com',
#                        'finextra.com',
#                        'fintechnews.sg',
#                        'fonearena.com',
#                        'ft.com',
#                        'gadgets360.com',
#                        'geekwire.com',
#                        'gizchina.com',
#                        'gizmochina.com',
#                        'gizmodo.com',
#                        'gsmarena.com',
#                        'hackernoon.com',
#                        'howtogeek.com',
#                        'ibtimes.co.uk',
#                        'itwire.com',
#                        'lifehacker.com',
#                        'macrumors.com',
#                        'mashable.com',
#                        #  'medium.com',
#                        'mobileworldlive.com',
#                        'msn.com',
#                        'nypost.com',
#                        'phonearena.com',
#                        'phys.org',
#                        'popsci.com',
#                        'scmp.com',
#                        'sify.com',
#                        'siliconangle.com',
#                        'siliconera.com',
#                        'siliconrepublic.com',
#                        'slashdot.org',
#                        'slashgear.com',
#                        'statnews.com',
#                        'tech.co',
#                        'techcrunch.com',
#                        'techdirt.com',
#                        'technode.com',
#                        'technologyreview.com',
#                        'techopedia.com',
#                        'techradar.com',
#                        'techraptor.net',
#                        'techtimes.com',
#                        'techxplore.com',
#                        'telecomtalk.info',
#                        'thecut.com',
#                        'thedrum.com',
#                        'thehill.com',
#                        'theregister.com',
#                        'theverge.com',
#                        'thurrott.com',
#                        'tipranks.com',
#                        'tweaktown.com',
#                        'videocardz.com',
#                        'washingtonpost.com',
#                        'wccftech.com',
#                        'wired.com',
#                        'xda-developers.com',
#                        'yahoo.com',
#                        'zdnet.com']

######################################################################
